[terminal]
default_shell = ""

[advanced]
scrollback_limit_bytes = 10000000

[keys]
prefix = "ctrl+space"
reload_config = "prefix+shift+q"
goto = "prefix+g"

# Panel splits
split_vertical = "prefix+|"
split_horizontal = "prefix+_"
close_pane = "prefix+x"

# Window management
rename_tab = "prefix+r"
new_tab = "prefix+c"
# close_tab = "prefix+X"

# Workspace management
rename_workspace = "prefix+shift+r"
new_workspace = "prefix+shift+c"
close_workspace = "prefix+shift+x"
previous_workspace = "prefix+shift+p"
next_workspace = "prefix+shift+n"

# Commands
[[keys.command]]
key = "prefix+t"
type = "popup"
command = "exec \"${SHELL:-sh}\""
description = "open scratch terminal"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+alt+g"
type = "popup"
command = "lazygit"
description = "run lazygit"
width = "80%"
height = "80%"

[ui]
mouse_capture = false

[theme]
name = "tokyo-night"
auto_switch = true
light_name = "tokyo-night-day"
dark_name = "tokyo-night"
